#Будем сразу принимать вещественные числа, т.к. на вход могут попасть именно такие. Можно сделать проверку, но зачем усложнять.
print("Введите первое число:", end=" ")
a = float(input())
print("Введите второе число:", end=" ")
b = float(input())
print("{0}+{1}={2}".format(a, b, a+b))
print("{0}-{1}={2}".format(a, b, a-b))
print("{0}*{1}={2}".format(a, b, a*b))
print("{0}/{1}={2}".format(a, b, a/b))
print("{0}^{1}={2}".format(a, b, a**b))
print("{0}%{1}={2}".format(a, b, a%b))
print("{0}//{1}={2}".format(a, b, a//b))
